/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"
#include "canvas.h"
#include "my_data.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp {
public:
	virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

class MainFrame : public MainFrameBase {
public:
	MainFrame( wxWindow *parent );
	virtual ~MainFrame();

protected:
	// protected event handlerss
	virtual void OnCloseFrame( wxCloseEvent& event );
	virtual void OnExitClick( wxCommandEvent& event );

	void m_loadfileOnMenuSelection(wxCommandEvent& event);
	void m_loaddataOnMenuSelection(wxCommandEvent& event);
	void m_savedataOnMenuSelection(wxCommandEvent& event);
	void m_aboutOnMenuSelection(wxCommandEvent& event);

private:
	bool m_isLoad; //flag  where is the map  loaded
};

#endif //__main__
